name: pin_lock_screen
description: Easily integrate a secure screen lock PIN feature into your Flutter application with the pin_lock_screen package. This versatile package provides a seamless solution for enhancing the privacy and security of your app by allowing users to set and require a PIN to access sensitive content or features.
version: 0.0.1
homepage: https://github.com/xubair305/pin_lock_screen

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:
